### ISSUE TITLE
update to weldx 0.4.0

### ISSUE THREAD

**Issue by CagtayFabry** [BAMWelDX/IIW2021_joint_intermediate_CXII#8]
- [ ] add spatial scan data to weldx file
- [ ] update schemas and tutorial notebook descriptions
- [ ] update syntax
- [ ] use `WeldxFile`

**Comment by CagtayFabry** [comment]
@vhirtham 
can you please take a look at the notebook in next next couple of days and check against the current `weldx` master?
I think with some of the new features it should be a lot more concise :)

I will prepare the dataset for the upcoming talk afterwards

**Comment by vhirtham** [comment]
> @vhirtham
> can you please take a look at the notebook in next next couple of days and check against the current `weldx` master?
> I think with some of the new features it should be a lot more concise :)

I will update as much as I can 😉

**Comment by CagtayFabry** [comment]
thanks, probably best to do it on a separate branch since I will create a new repo anyway

**Comment by CagtayFabry** [comment]
see https://github.com/BAMWelDX/IIW2021_AA_CXII
